import 'package:flutter/material.dart';

const Color kPrimary      = Color(0xFFF9C413);
const Color kPrimaryDark  = Color(0xFFE0AC00);
const Color kPrimaryPale  = Color(0xFFFFFBE6);
const Color kBg           = Color(0xFFFAF9F5);
const Color kCard         = Color(0xFFFFFFFF);
const Color kDark         = Color(0xFF1C1B1A);
const Color kMid          = Color(0xFF888880);
const Color kBorder       = Color(0xFFEEEDEA);

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kBg,
      appBar: AppBar(
        backgroundColor: kCard,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: kDark, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'PRIVACY POLICY',
          style: TextStyle(
            color: kDark,
            fontSize: 16,
            fontWeight: FontWeight.w800,
            letterSpacing: 0.5,
          ),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.all(20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: kPrimaryPale,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: kPrimary.withOpacity(0.3), width: 1.5),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        const Icon(Icons.shield_outlined, color: kPrimaryDark, size: 24),
                        const SizedBox(width: 8),
                        Text(
                          'Privacy Policy',
                          style: TextStyle(
                            color: kDark,
                            fontSize: 18,
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Last updated: April 29, 2024',
                      style: TextStyle(color: kMid, fontSize: 13, fontWeight: FontWeight.w600),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
              const Text(
                'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\nWe use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
                style: TextStyle(fontSize: 14.5, color: kDark, height: 1.6),
              ),
              const SizedBox(height: 24),
              _sectionHeader('Interpretation & Definitions'),
              _subHeader('Interpretation'),
              _bodyText(
                'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
              ),
              _subHeader('Definitions'),
              _bodyText('For the purposes of this Privacy Policy:'),
              _bulletPoint('Account', 'means a unique account created for You to access our Service or parts of our Service.'),
              _bulletPoint('Company', 'refers to Mr Coach, 38A/98 KalathuMettu Street, Chengalpattu-603002.'),
              _bulletPoint('Country', 'refers to: Tamil Nadu, India'),
              _bulletPoint('Device', 'means any device that can access the Service such as a cellphone, tablet, or computer.'),
              _bulletPoint('Personal Data', 'is any information that relates to an identified or identifiable individual.'),
              _bulletPoint('Service', 'refers to the Mobile Application & Website.'),
              _bulletPoint('Usage Data', 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.'),
              const SizedBox(height: 24),
              _sectionHeader('Collecting and Using Your Personal Data'),
              _subHeader('Types of Data Collected'),
              _boldLabel('Personal Data'),
              _bodyText(
                'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n• Email address\n• First name and last name\n• Phone number\n• Address, State, Province, ZIP/Postal code, City\n• Usage Data',
              ),
              _boldLabel('Usage Data'),
              _bodyText(
                'Usage Data is collected automatically when using the Service. It may include information such as Your Device\'s Internet Protocol address (e.g. IP address), unique device identifiers, device type, operating system, and diagnostic data.',
              ),
              _boldLabel('Information from Third-Party Services'),
              _bodyText(
                'The Company allows You to create an account and log in to use the Service through Google or other social networks. If You decide to register through a Third-Party Social Media Service, We may collect Personal data already associated with that account (e.g. name, email).',
              ),
              const SizedBox(height: 24),
              _sectionHeader('Use of Your Personal Data'),
              _bodyText('The Company may use Personal Data for the following purposes:'),
              _bulletPoint('To provide and maintain our Service', 'including to monitor the usage of our Service.'),
              _bulletPoint('To manage Your Account', 'to manage Your registration as a user of the Service.'),
              _bulletPoint('For the performance of a contract', 'the development, compliance and undertaking of the purchase contract for products or services.'),
              _bulletPoint('To contact You', 'by email, telephone calls, SMS, or equivalent forms of electronic communication regarding updates or informative communications.'),
              _bulletPoint('To provide news & offers', 'about goods, services, and events similar to those you already purchased/enquired about.'),
              _bulletPoint('To manage Your requests', 'to attend and manage Your requests to Us.'),
              const SizedBox(height: 24),
              _sectionHeader('Retention and Security of Your Data'),
              _bodyText(
                'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We take all steps reasonably necessary to ensure that Your data is treated securely.\n\nWhile We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
              ),
              const SizedBox(height: 24),
              _sectionHeader('Delete Your Personal Data'),
              _bodyText(
                'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service gives You the ability to delete certain information from within the settings page or request account deletion.',
              ),
              const SizedBox(height: 24),
              _sectionHeader('Contact Us'),
              _bodyText('If you have any questions about this Privacy Policy, You can contact us:'),
              _bulletPoint('Email', 'mrcoachofficial@gmail.com'),
              _bulletPoint('Website', 'https://mrcoach.in/contact-us/'),
              _bulletPoint('Phone', '+91 74484 21134'),
              _bulletPoint('Address', '38A/98 KalathuMettu Street, Chengalpattu, Tamil Nadu, 603002'),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _sectionHeader(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Text(
        title,
        style: const TextStyle(
          color: kDark,
          fontSize: 16,
          fontWeight: FontWeight.w900,
          letterSpacing: 0.3,
        ),
      ),
    );
  }

  Widget _subHeader(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
      child: Text(
        title,
        style: const TextStyle(
          color: kDark,
          fontSize: 15,
          fontWeight: FontWeight.w800,
        ),
      ),
    );
  }

  Widget _boldLabel(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 10.0, bottom: 6.0),
      child: Text(
        title,
        style: const TextStyle(
          color: kDark,
          fontSize: 14,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }

  Widget _bodyText(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 14.0),
      child: Text(
        text,
        style: const TextStyle(
          fontSize: 14,
          color: kDark,
          height: 1.5,
        ),
      ),
    );
  }

  Widget _bulletPoint(String term, String definition) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0, left: 8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('• ', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: kPrimaryDark)),
          Expanded(
            child: RichText(
              text: TextSpan(
                style: const TextStyle(fontSize: 14, color: kDark, height: 1.4),
                children: [
                  TextSpan(text: '$term: ', style: const TextStyle(fontWeight: FontWeight.bold)),
                  TextSpan(text: definition),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kBg,
      appBar: AppBar(
        backgroundColor: kCard,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: kDark, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'TERMS OF SERVICE',
          style: TextStyle(
            color: kDark,
            fontSize: 16,
            fontWeight: FontWeight.w800,
            letterSpacing: 0.5,
          ),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.all(20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: kPrimaryPale,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: kPrimary.withOpacity(0.3), width: 1.5),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        const Icon(Icons.description_outlined, color: kPrimaryDark, size: 24),
                        const SizedBox(width: 8),
                        Text(
                          'Terms & Conditions',
                          style: TextStyle(
                            color: kDark,
                            fontSize: 18,
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    const Text(
                      'Last updated: March 26, 2024',
                      style: TextStyle(color: kMid, fontSize: 13, fontWeight: FontWeight.w600),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
              const Text(
                'For the purpose of these Terms and Conditions, The term “we”, “us”, “our” used anywhere on this page shall mean Mr.COACH FIT, whose registered/operational office is 38A/98, KalathuMettu Street, Chengalpattu, Chengalpattu Chengalpattu TAMIL NADU 603002. “you”, “your”, “user”, “visitor” shall mean any natural or legal person who is visiting our website and/or agreed to purchase from us.',
                style: TextStyle(fontSize: 14.5, color: kDark, height: 1.6),
              ),
              const SizedBox(height: 24),
              _sectionHeader('Governing Rules & Operations'),
              _bodyText('Your use of the application and/or purchase from us are governed by the following Terms and Conditions:'),
              _bulletPoint('Changes', 'The content of the pages of this website/app is subject to change without notice.'),
              _bulletPoint('No Warranty', 'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered.'),
              _bulletPoint('User Risk', 'Your use of any information or materials on our website and/or product pages is entirely at your own risk, for which we shall not be liable.'),
              _bulletPoint('Intellectual Property', 'This material includes, but is not limited to, the design, layout, look, appearance, and graphics. Reproduction is prohibited.'),
              _bulletPoint('Trademarks', 'All trademarks reproduced in this app which are not the property of, or licensed to, the operator are acknowledged.'),
              _bulletPoint('Unauthorized Use', 'Unauthorized use of information provided by us shall give rise to a claim for damages and/or be a criminal offense.'),
              _bulletPoint('External Links', 'From time to time our website/app may also include links to other websites. These links are provided for your convenience to provide further information.'),
              _bulletPoint('Disputes', 'Any dispute arising out of use of our website and/or purchase with us and/or any engagement with us is subject to the laws of India.'),
              _bulletPoint('Transaction Liability', 'We shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.'),
              const SizedBox(height: 24),
              _sectionHeader('Disclaimer'),
              _bodyText(
                'The above content is created at Mr.COACH FIT’s sole discretion. Razorpay shall not be liable for any content provided here and shall not be responsible for any claims and liability that may arise due to merchant’s non-adherence to it.',
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _sectionHeader(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Text(
        title,
        style: const TextStyle(
          color: kDark,
          fontSize: 16,
          fontWeight: FontWeight.w900,
          letterSpacing: 0.3,
        ),
      ),
    );
  }

  Widget _bodyText(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 14.0),
      child: Text(
        text,
        style: const TextStyle(
          fontSize: 14,
          color: kDark,
          height: 1.5,
        ),
      ),
    );
  }

  Widget _bulletPoint(String term, String definition) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10.0, left: 8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('• ', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: kPrimaryDark)),
          Expanded(
            child: RichText(
              text: TextSpan(
                style: const TextStyle(fontSize: 14, color: kDark, height: 1.4),
                children: [
                  TextSpan(text: '$term: ', style: const TextStyle(fontWeight: FontWeight.bold)),
                  TextSpan(text: definition),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
