import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations {
  static String currentLanguage = 'EN'; // 'EN', 'TA', 'HI'

  static const Map<String, Map<String, String>> _localizedValues = {
    'EN': {
      'profile_title': 'My Profile',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'change_password': 'Change Password',
      'language': 'Language',
      'gender': 'Gender',
      'age': 'Age',
      'date_of_birth': 'Date of Birth',
      'area': 'Area',
      'pincode': 'Pincode',
      'district': 'District',
      'state': 'State',
      'service_type': 'Service Type',
      'preferred_language': 'Preferred Language',
      'alternate_phone': 'Alternate Phone',
      'address': 'Address',
      'emergency_contact': 'Emergency Contact',
      'fitness_goal': 'Fitness Goal',
      'verify_otp': 'Verify OTP',
      'enter_otp': 'Enter OTP',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'otp_sent': 'OTP Sent',
      'resend_otp': 'Resend OTP',
      'logout': 'Log Out',
      'login': 'Log In / Register',
      'delete_account': 'Delete Account',
      'member': 'MrCoach Member',
      'account': 'ACCOUNT',
      'notifications': 'NOTIFICATIONS',
      'app_info': 'APP INFO',
      'actions': 'ACCOUNT ACTIONS',
      'choose_language': 'Choose Preferred Language',
      'reset_link_sent': 'Password Reset OTP will be sent to your email',
      'profile_updated': 'Profile updated ✓',
      'profile_image_removed': 'Profile image removed ✓',
      'profile_image_updated': 'Profile image updated ✓',
      'failed_to_update': 'Failed to update profile',
      'loading': 'Loading...',
      'otp_sent_to_email': 'OTP sent to registered email',
      'password_changed_success': 'Password updated successfully ✓. Please log in again.',
      'enter_valid_otp': 'Please enter a valid 6-digit OTP',
      'enter_all_fields': 'Please fill all password fields',
    },
    'TA': {
      'profile_title': 'எனது சுயவிவரம்',
      'edit_profile': 'சுயவிவரத்தைத் திருத்து',
      'save_changes': 'மாற்றங்களைச் சேமி',
      'cancel': 'ரத்துசெய்',
      'change_password': 'கடவுச்சொல்லை மாற்று',
      'language': 'மொழி',
      'gender': 'பாலினம்',
      'age': 'வயது',
      'date_of_birth': 'பிறந்த தேதி',
      'area': 'பகுதி',
      'pincode': 'பின்கோடு',
      'district': 'மாவட்டம்',
      'state': 'மாநிலம்',
      'service_type': 'சேவை வகை',
      'preferred_language': 'விருப்பமான மொழி',
      'alternate_phone': 'மாற்று தொலைபேசி எண்',
      'address': 'முகவரி',
      'emergency_contact': 'அவசர தொடர்பு',
      'fitness_goal': 'உடற்பயிற்சி இலக்கு',
      'verify_otp': 'OTP சரிபார்க்கவும்',
      'enter_otp': 'OTP ஐ உள்ளிடவும்',
      'current_password': 'தற்போதைய கடவுச்சொல்',
      'new_password': 'புதிய கடவுச்சொல்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'otp_sent': 'OTP அனுப்பப்பட்டது',
      'resend_otp': 'OTP ஐ மீண்டும் அனுப்பு',
      'logout': 'வெளியேறு',
      'login': 'உள்நுழைய / பதிவுசெய்ய',
      'delete_account': 'கணக்கை நீக்கு',
      'member': 'MrCoach உறுப்பினர்',
      'account': 'கணக்கு',
      'notifications': 'அறிவிப்புகள்',
      'app_info': 'செயலி தகவல்',
      'actions': 'கணக்கு நடவடிக்கைகள்',
      'choose_language': 'விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      'reset_link_sent': 'கடவுச்சொல் மாற்றுவதற்கான OTP மின்னஞ்சலுக்கு அனுப்பப்படும்',
      'profile_updated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது ✓',
      'profile_image_removed': 'சுயவிவரப் படம் அகற்றப்பட்டது ✓',
      'profile_image_updated': 'சுயவிவரப் படம் புதுப்பிக்கப்பட்டது ✓',
      'failed_to_update': 'சுயவிவரத்தைப் புதுப்பிக்க முடியவில்லை',
      'loading': 'ஏற்றுகிறது...',
      'otp_sent_to_email': 'பதிவு செய்யப்பட்ட மின்னஞ்சலுக்கு OTP அனுப்பப்பட்டது',
      'password_changed_success': 'கடவுச்சொல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது ✓. மீண்டும் உள்நுழையவும்.',
      'enter_valid_otp': 'முறையான 6 இலக்க OTP ஐ உள்ளிடவும்',
      'enter_all_fields': 'அனைத்து கடவுச்சொல் கட்டங்களையும் நிரப்பவும்',
    },
    'HI': {
      'profile_title': 'मेरी प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'save_changes': 'बदलाव सहेजें',
      'cancel': 'रद्द करें',
      'change_password': 'पासवर्ड बदलें',
      'language': 'भाषा',
      'gender': 'लिंग',
      'age': 'आयु',
      'date_of_birth': 'जन्म तिथि',
      'area': 'क्षेत्र',
      'pincode': 'पिनकोड',
      'district': 'जिला',
      'state': 'राज्य',
      'service_type': 'सेवा का प्रकार',
      'preferred_language': 'पसंदीदा भाषा',
      'alternate_phone': 'वैकल्पिक फ़ोन',
      'address': 'पता',
      'emergency_contact': 'आपातकालीन संपर्क',
      'fitness_goal': 'फिटनेस लक्ष्य',
      'verify_otp': 'ओटीपी सत्यापित करें',
      'enter_otp': 'ओटीपी दर्ज करें',
      'current_password': 'वर्तमान पासवर्ड',
      'new_password': 'नया पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'otp_sent': 'ओटीपी भेजा गया',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'logout': 'लॉग आउट',
      'login': 'लॉग इन / रजिस्टर',
      'delete_account': 'खाता हटाएं',
      'member': 'MrCoach सदस्य',
      'account': 'खाता',
      'notifications': 'अधिसूचनाएं',
      'app_info': 'ऐप जानकारी',
      'actions': 'खाता गतिविधियां',
      'choose_language': 'पसंदीदा भाषा चुनें',
      'reset_link_sent': 'पासवर्ड रीसेट ओटीपी आपके ईमेल पर भेजा जाएगा',
      'profile_updated': 'प्रोफ़ाइल अपडेट हो गई है ✓',
      'profile_image_removed': 'प्रोफ़ाइल छवि हटा दी गई है ✓',
      'profile_image_updated': 'प्रोफ़ाइल छवि अपडेट हो गई है ✓',
      'failed_to_update': 'प्रोफ़ाइल अपडेट करने में विफल',
      'loading': 'लोड हो रहा है...',
      'otp_sent_to_email': 'पंजीकृत ईमेल पर ओटीपी भेज दिया गया है',
      'password_changed_success': 'पासवर्ड सफलतापूर्वक अपडेट किया गया ✓। कृपया दोबारा लॉग इन करें।',
      'enter_valid_otp': 'कृपया एक वैध 6-अंकीय ओटीपी दर्ज करें',
      'enter_all_fields': 'कृपया सभी पासवर्ड फ़ील्ड भरें',
    }
  };

  static String translate(String key) {
    return _localizedValues[currentLanguage]?[key] ?? _localizedValues['EN']?[key] ?? key;
  }

  // Load language preference from SharedPreferences
  static Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    currentLanguage = prefs.getString('app_lang') ?? 'EN';
  }

  // Save language preference to SharedPreferences
  static Future<void> saveLanguage(String lang) async {
    currentLanguage = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_lang', lang);
  }
}
